<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\Contact\" />
    <Folder Include="Models\Properties\Details\" />
    <Folder Include="Views\Contact\" />
    <Folder Include="Views\Properties\" />
    <Folder Include="Views\Shared\PropertieDetails\" />
  </ItemGroup>

</Project>
